config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  post '/' => 'main#choice'
  # ~~~~~~~~~Trails~~~~~~~~~~~
  post '/trail/show' => 'trail#show'
  get '/trail/show' => 'trail#show'
  get '/trail/maps'  => 'trail#maps'

  #~~~~~~~~~~~youtube~~~~~~~~~~~~~
  get 'you_tube_controller/search'
  post 'you_tube_controller/search'
  get 'you_tube_controller/tubeSearch'

  #~~~~~~~~~~~spotify~~~~~~~~~~~~~
  get '/music' => 'music#show'
  get '/auth/spotify/callback', to: 'music#spotify'
  get '/auth/logout' => 'music#logout'
  get '/auth/failure' => 'music#failure'

  #~~~~~~~~~~~~trivia~~~~~~~~~~~~~
  get 'trivia' => 'trivia#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/trail_controller.rb
class TrailController < ApplicationController
  def index
  end

  def show
    gon.choice = $choice
    hike_response = HTTParty.get "https://trailapi-trailapi.p.mashape.com/?limit=25&q[activities_activity_type_name_eq]=hiking&q[state_cont]=Washington&radius=25",
      headers:{
        "X-Mashape-Key" => "gKkZRWGHnsmsh9H4030c2YJirj8mp1co61Djsntmdy8iYTxtf7",
        "Accept" => "text/plain"
    }
  	$hikes = []
  	if hike_response.code == 200
      @hike_result = JSON.parse(hike_response.body)
      for place in @hike_result['places']
          $mode !='' ? place['mode'] = $mode : place['mode'] = 'driving'
          $location != '' ? place['origin'] = $location : place['origin'] = 'Seattle'
          $hikes.push(place)
      end
  	end
  end

  def maps
    @loops = ($hikes.size.to_i)
    for i in (0...@loops)
      map_response = HTTParty.get "https://maps.googleapis.com/maps/api/directions/json", {
        query: {
          origin: $hikes[i]['origin'],
          destination: $hikes[i]['lat'].to_s+","+$hikes[i]['lon'].to_s,
          mode: $hikes[i]['mode']
        }
      }
      @map = nil
      if map_response.code == 200 and map_response['status'] == "OK"
        @map = JSON.parse(map_response.body)
        @end_address = @map['routes'][0]['legs'][0]['end_address']
        @distance = @map['routes'][0]['legs'][0]['distance']
        @duration = @map['routes'][0]['legs'][0]['duration']
        $hikes[i]['end_address'] = @end_address
        $hikes[i]['distance'] = @distance
        $hikes[i]['duration'] = @duration
        $hikes[i]['roundtrip'] = ($hikes[i]['duration']['value'].to_i/60*2 + $hikes[i]['activities'][0]['length'].to_i/3.1*60).to_i
      end
      weather_response = HTTParty.get "http://api.openweathermap.org/data/2.5/weather", {
        query: {
          lat: $hikes[i]['lat'],
          lon: $hikes[i]['lon'],
          APPID: ENV['WEATHER_KEY']
        }
      }
      @weather = JSON.parse(weather_response.body)
      $hikes[i]['weather'] = ((9*(@weather['main']['temp']-273)/5)+32).round
        if ($hikes[i]['roundtrip'].class == NilClass)
          $hikes[i]['roundtrip'] = 0
        end
    end
    $hikes.sort_by!{ |k| k["roundtrip"]}
    render :partial => "maps"
  end
end

app/views/trail/_maps.html.erb
<div class="hikes-loaded">
	<h2>Chronotron Outdoors</h2>
	<%for i in (0...@loops)%>
	<%if $hikes[i]['distance'] and $hikes[i]['roundtrip'] <= $time.to_i%>
		<div class="hike">
			<div class="hike-info">
				<h3><span><%=$hikes[i]['name']%></span></h3>
				<div class="temp info-bit">
					Current Temp: <span><%=$hikes[i]['weather']%></span>&#x2109;
				</div>
				<div class="length info-bit">
					Length of Hike: <span><%=$hikes[i]['activities'][0]['length']%></span> miles
				</div>
				<div class="roundtrip info-bit">
					Total time roundtrip: <span><%=$hikes[i]['roundtrip']%> minutes</span>
				</div>
				<div class="address info-bit">
					Address: <span><%=$hikes[i]['end_address']%></span>
				</div>
				<div class="description info-bit">
					<span><%=$hikes[i]['activities'][0]['description']%></span>
				</div>
				</div>
				<div class="map">
					<iframe
					  width="600"
					  height="450"
					  frameborder="0" style="border:0"
					  src= <%='https://www.google.com/maps/embed/v1/place?key='+ENV['MAP_EMBED_KEY']+'&q='+$hikes[i]['lat'].to_s+','+$hikes[i]['lon'].to_s%> allowfullscreen>
					</iframe>
				</div>
		</div>
	<%end%>
	<%end%>
	<div class="no-hikes" hidden>
		<h3>Does Not Compute</h3>
		<h4>Chronotron couldn't find any hikes or parks that fit your time constraints. Use the sidebar, or <a href="/">return to the homepage</a>, to search again.</h4>
	</div>
	<script>
		if($(".hike").length === 0){
			$('.no-hikes').show();
		}
	</script>
</div>

app/views/trail/index.html.erb
<div class="category trail-pg">
	<div class="trail-content">
		<h2>Chronotron Outdoors</h2>
		<div class="trail-search">
			<p>How are you planning to get there?</p>
				<%= form_tag("/trail/show", method: "post") do %>
				  <%= label_tag(:mode, "I'll be") %>
				  <%= select_tag(:mode, options_for_select([['walking', 'walking'], ['driving', 'driving'], ['bicycling', 'bicycling']]))%>
				  <%= submit_tag("Search") %>
				<% end %>
			</div>
		</div>
</div>

app/views/trail/show.html.erb
<div class="category">
	<div class="trail-results">
	<%= render_async trail_maps_path%>
		<div id="spinner" class="trails-loading"><h2>
			Loading...
		</h2>
		</div>
		<script>
			$(document).ajaxStop(function(){
				$('#spinner').hide();
			});
		</script>
	</div>
</div>